import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function HomePage() {
  return (
    <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-16 px-4 py-12 sm:px-6 sm:py-20">
      <section className="max-w-3xl">
        <p className="mb-4 text-sm font-medium tracking-wide text-primary uppercase">
          Verdict first
        </p>
        <h1 className="font-heading text-4xl leading-tight text-balance sm:text-6xl">
          You can make money boosting influencer accounts. You cannot do it with fake followers.
        </h1>
        <p className="mt-6 max-w-2xl text-lg text-muted-foreground text-pretty">
          Selling likes, views, comments, or followers generated by bots is not a gray-area hustle
          in the US anymore. It is an FTC trade-rule violation. The product that still works is
          software that makes a real account easier to grow and easier to sell to brands.
        </p>
        <div className="mt-8 flex flex-wrap gap-3">
          <Button nativeButton={false} render={<Link href="/studio" />} size="lg">
            Run a growth plan
          </Button>
          <Button nativeButton={false} render={<Link href="/brief" />} variant="outline" size="lg">
            Legal and money brief
          </Button>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle>Illegal to sell</CardTitle>
            <CardDescription>16 CFR 465.8, in force since 21 Oct 2024</CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            Anyone who sells or buys fake indicators of social media influence — followers, friends,
            views, likes, comments — for a commercial purpose, knowing they are fake, is breaking
            the rule. Penalties are civil and per violation, currently north of $50,000 each. Bot
            farms that smash login walls can also trip the Computer Fraud and Abuse Act.
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Legal, and already a market</CardTitle>
            <CardDescription>Scheduling, analytics, media kits, fraud checks</CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            Official APIs let you schedule posts. Creators will pay for a posting system, a honest
            rate card, and a warning when their own numbers look purchased. Later, Buffer, Metricool,
            and CreatorIQ already bill for this. The gap is a cheap studio for nano and micro
            accounts that brands still refuse to trust.
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Where the money is</CardTitle>
            <CardDescription>$12–$29/mo creators, or B2B authenticity</CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            Two hundred people on a $19 plan is about $3,800 a month. One thousand is $19,000. The
            quieter, better business is selling the same authenticity check to brands so they stop
            wiring $4,000 to a fake 80k. Fake-engagement shops eat chargebacks and FTC letters.
          </CardContent>
        </Card>
      </section>
    </main>
  );
}
